<?xml version="1.0" encoding="utf-8"?><Database Name="VehicleServicing" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\VehicleServicing.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="VehicleServicingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Forename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Customer_Vehicle" Member="Vehicles" ThisKey="ID" OtherKey="CustomerID" Type="Vehicle" />
    </Type>
  </Table>
  <Table Name="dbo.Vehicles" Member="Vehicles">
    <Type Name="Vehicle">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Make" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Variation" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FuelType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Vehicle_VehicleService" Member="VehicleServices" ThisKey="ID" OtherKey="VehicleID" Type="VehicleService" />
      <Association Name="Customer_Vehicle" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VehicleServices" Member="VehicleServices">
    <Type Name="VehicleService">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VehicleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MechanicName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ServiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Vehicle_VehicleService" Member="Vehicle" ThisKey="VehicleID" OtherKey="ID" Type="Vehicle" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.InsertServiceDetailProcedure" Method="InsertServiceDetailProcedure">
    <Parameter Name="VehicleID" Parameter="vehicleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MechanicName" Parameter="mechanicName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="Text" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Money" />
    <Parameter Name="ServiceDate" Parameter="serviceDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SearchCustomerProcedure" Method="SearchCustomerProcedure">
    <Parameter Name="forename" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="surname" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="postcode" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="SearchCustomerProcedureResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Forename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectCustomerProcedure" Method="SelectCustomerProcedure">
    <Parameter Name="customerId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectCustomerProcedureResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Forename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
</Database>